/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_INTERP_PREFIX "/usr/gnemul/qemu-x86_64"
#define TARGET_ARCH "x86_64"
#define TARGET_X86_64 1
#define TARGET_I386 1
#define CONFIG_KVM 1
#define CONFIG_KVM_PARA 1
#define TARGET_PHYS_ADDR_BITS 64
#define CONFIG_SOFTMMU 1
#define CONFIG_NOSOFTFLOAT 1
#define CONFIG_I386_DIS 1
#define CONFIG_I386_DIS 1
#define CONFIG_PVC 1
#define CONFIG_PVC_SCC 1
